This game is inspired by Hearthstone and is like, a two-player (or two-computer) game in which each player draws card units from a set, places them on their side of the board and then let the units fight each other.

At the end of each battle, the ammount of units left on each side translates to the total damage dealt to the opposing player. When a player reaches 0 HP, the game is over.

Some ideas:

- Have multiple matrices (overlaying boards) for attack value and defense values for each unit, not just health.
    - Or just have vectors in the matrice containing stats for the unit??
    - if we do this, another layout would be needed, as the current layout only handles one value for each unit
    - but it would be cool to do and make it much more interesting and lärorikt i guess

    <br>

- Have units which buffs other units if they are placed next to them.

- Have units merge if they are similar in some way??
    - This also means having to create different unit-types, which would be fun!

    <br>

- Have units move to different spaces. This is an intersting one. Maybe attack could increase if some units are closer?

TODO:

How should the units be distributed between the players? How should it be randomized? Just draw a couple from a deck probably.

Adjust attack patterns. Right now its simply just row subtraction.


Also, this is written to work with jupyter notebook, some adjustments needed for .py to avoid re-running functions etc.

In [1]:
# Generating board, any 2 dimensional size should work
import numpy as np
board = np.zeros((4,4)) # but lower are better for testing
print(board)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
# Player health, players lose one HP per unit left on opponent side after battle phase
P1_health = len(board) * 10
P2_health = len(board) * 10

# Player name
P1 = 'P1 Fried'
P2 = 'P2 Toast'

# Testing health values of units in hand to be placed on the board
# this should probably be a hand drawn from a deck, like, draw one card each turn, start with 3 or smt
# maybe write algos to make predictions on which cards to play
# i mean at the current state the best algo would just play the card with the highest health value, but adding more parameters could make it interesting
P1_hand = [2,0,0]
P2_hand = [2,0,0]

# if we do the vector idea (which we totally should) these would represent playable card units
# rn for testing it only represents UNIT HEALTH 
P1_deck = [1,2,3,4,5,6,7,8,9]
P2_deck = [1,2,3,4,5,6,7,8,9]

# pretty good function, works with lists
np.random.shuffle(P1_deck)
np.random.shuffle(P2_deck)

P1_deck, P2_deck

([4, 7, 1, 6, 5, 8, 9, 2, 3], [5, 2, 6, 9, 8, 7, 1, 3, 4])

In [3]:
def draw_card(player, hand, deck):
    print(f'{draw_card} running for {player}')

    # If hand is full
    if np.count_nonzero(hand) >= len(hand):
        return None

    for i, card in enumerate(hand):
        if card == 0:
            break
        print(f'Current {hand=}')
    print(f'Card drawn={deck[0]}')
    hand[i] = deck[0]
    print(f'New {hand=}')
    deck.pop(0)

    return hand, deck

def remove_card(player, hand):
    hand.pop(0)
    hand.append(0)
    print(f'Card removed from {player} hand')
    return hand


def select_card(player, hand):
    pass
    

In [4]:
try:
    P1_hand, P1_deck = draw_card(P1, P1_hand, P1_deck)

except:
    print(f'Hand is full = {P1_hand}. {draw_card} aborted!')

<function draw_card at 0x11e7940d0> running for P1 Fried
Current hand=[2, 0, 0]
Card drawn=4
New hand=[2, 4, 0]


In [5]:
P1_hand = remove_card(P1,P1_hand)
P1_hand

Card removed from P1 Fried hand


[4, 0, 0]

In [6]:
def place_unit(board, player, player_hand):

    # max values might not be needed after all, but good for testing different board sizes
    max_width = len(board[0])-1
    max_height = len(board)-1

    print(f'{board.shape=}, placing unit for {player}')

    try:
        x, y = select_tile(board, max_width, max_height, player) # tuple unpacking of coords for unit placement

        
        board[x,y] = player_hand[0]

        print(f'{player} placed a unit with health {player_hand[0]} at {[x+1,y+1]}')
        return board

    except:
        print(f'Cannot find tile, {player} unit row is full!')
        return board

def select_tile(board, max_x, max_y, player) -> tuple:
    """Finds available tile to place unit on board.
    Starts on the left and continues for each available column for each player
    TODO: Maybe shuffle units, or make old units get pushed to the right once new ones are placed?
    """

    print(f'{select_tile} running for {player=}')

    # if board is full for either player, return None
    if player == P1 and board[max_x][-1] != 0 or player == P2 and board[0][-1] !=0:
        return None

    # find available tile for P1 (bottom row) and P2 (top row)
    if player == P1:
        row = max_x
        column = 0
        while board[row][column] != 0:
            column +=1
        return row, column

    #P2
    row = 0
    column = 0
    while board[row][column] != 0:
        column +=1
    return row, column

place_unit(board, player=P1, player_hand=P1_hand)

board.shape=(4, 4), placing unit for P1 Fried
<function select_tile at 0x11c782f70> running for player='P1 Fried'
P1 Fried placed a unit with health 4 at [4, 1]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 0., 0., 0.]])

In [7]:
# testing to place basic units
for length in board:
    place_unit(board, player=P1, player_hand=P1_hand)
    place_unit(board, player=P2, player_hand=P2_hand)
board

board.shape=(4, 4), placing unit for P1 Fried
<function select_tile at 0x11c782f70> running for player='P1 Fried'
P1 Fried placed a unit with health 4 at [4, 2]
board.shape=(4, 4), placing unit for P2 Toast
<function select_tile at 0x11c782f70> running for player='P2 Toast'
P2 Toast placed a unit with health 2 at [1, 1]
board.shape=(4, 4), placing unit for P1 Fried
<function select_tile at 0x11c782f70> running for player='P1 Fried'
P1 Fried placed a unit with health 4 at [4, 3]
board.shape=(4, 4), placing unit for P2 Toast
<function select_tile at 0x11c782f70> running for player='P2 Toast'
P2 Toast placed a unit with health 2 at [1, 2]
board.shape=(4, 4), placing unit for P1 Fried
<function select_tile at 0x11c782f70> running for player='P1 Fried'
P1 Fried placed a unit with health 4 at [4, 4]
board.shape=(4, 4), placing unit for P2 Toast
<function select_tile at 0x11c782f70> running for player='P2 Toast'
P2 Toast placed a unit with health 2 at [1, 3]
board.shape=(4, 4), placing unit f

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [4., 4., 4., 4.]])

In [8]:
def battle_phase(board, P1_health, P2_health):

    # so right now this is a very boring attack pattern, it just mirrors the same column values and subtracts
    P2_row = board[0]-board[-1]
    P1_row = board[-1]-board[0]

    # remove units if health is < 0
    board[0] = [0 if i < 0 else i for i in P2_row]
    board[-1] = [0 if i < 0 else i for i in P1_row]

    # count non-zero values for units left/damage dealt
    P2_units_left, P1_units_left = np.count_nonzero(board[0]), np.count_nonzero(board[-1])

    print(f'P2: {board[0]}, units left = {P2_units_left}')
    print(f'P1: {board[-1]}, units left = {P1_units_left}')

    if P2_units_left > P1_units_left:
        P1_health -= P2_units_left
        print(f'P2 dealt {P2_units_left} damage to P1.')

    elif P1_units_left > P2_units_left:
        P2_units_left -= P1_units_left
        print(f'P1 dealt {P1_units_left} damage to P2.')

    else:
        print('Draw, no damage dealt.')
    
    return board, P2_units_left, P1_units_left

board, P2_damage_dealt, P1_damage_dealt = battle_phase(board, P2_health, P1_health)

P1_health -= P2_damage_dealt
P2_health -= P1_damage_dealt
print(P1_health, P2_health)

P2: [0. 0. 0. 0.], units left = 0
P1: [2. 2. 2. 2.], units left = 4
P1 dealt 4 damage to P2.
44 36


The entire battle_phase will have to be refactored for multiple matrices. Maybe the best idea is to have the main board containing vectors which represents the unit, with each vector holding the health, attack etc. values?

But for now, it's just simply health and attack as the same value for the same position on the board.

So if for example we're left with this board:

```
P2: [1. 1. 1. 1.], units left = 4
P1: [0. 0. 0. 0.], units left = 0
P2 dealt 4 damage to P1.
````
P2 would not be able to place any more units the next turn. So we have to make a decision on how to handle that.
If we leave it as is, the player who wins the turn will be much less likely to win the next turn, given the remaining units will have on average much lower health, while P1 will be able to place new units with full health.

On the other hand, if we incorporate a 'card draw' mechanic, the player who's not able to place any units will have more cards(units) to place the next turn.

I guess we'll just have to experiment.

