### Linear systems of equations
- augmented matrix (utökad matris).
- Gaussian elimination
- reduced row echelon form (=reducerad trappstegsform) (sympy.rref)
- pivot columns, bound and free varibles

- scipy.linalg.solve

```x, y, z, pi = sp.symbols('x,y,z, pi')``` $= x, y, z, \pi$

In [205]:
import numpy as np
import sympy as sp

x, y, z, pi = sp.symbols('x,y,z, pi')

# Two dimensional array
a = np.array([[0,1,2],[pi,4,5],[-1,-2,-3]], dtype=object)

print(type(a), a.ndim, a.size, a.shape)
a


<class 'numpy.ndarray'> 2 9 (3, 3)


array([[0, 1, 2],
       [pi, 4, 5],
       [-1, -2, -3]], dtype=object)

In [206]:
# As sympy matrice (matrix)
sp.Matrix(a)

Matrix([
[ 0,  1,  2],
[pi,  4,  5],
[-1, -2, -3]])

In [207]:
# formats
n = 12
print('a = ', 2*np.sqrt(n)) # regualar print in IDE (prints result)
sp.pprint(2*sp.sqrt(n)) # prettyprinter module (prints expression)
2*sp.sqrt(n) # jupyter notebook output as sympy symbols (prints expression)

a =  6.928203230275509
4⋅√3


4*sqrt(3)

Sympy matrices are mutable while ndarrays are immutable.

 ---

## #Basic operations and conversions numpy/sympy

 Let's create a matrix and do some basic operations:

In [208]:
def get_grid():
    "Weird function, made another (also weird) one in course_log1"

    def get_row():

        # randomize key pair
        my_pair = np.random.randint([-8,0], [0,8])

         # appends random element from pool to end of key pair
        pool_of_constants = [pi, sp.Rational(2,3), 0, sp.Rational(1/4)]

        return np.append(my_pair, pool_of_constants[np.random.randint(0,4)])

    # create matrix
    a = np.array(
        [get_row(),
         get_row(),
         get_row()
    ])


    return a

a = get_grid()

sp.Matrix(a)

Matrix([
[-1, 5,   0],
[-2, 6,  pi],
[-5, 1, 1/4]])

In [209]:
r = sp.Rational(1,4)
print(r)

1/4


In [210]:
# fractions will not convert, issues with float to int type conversions probably

In [211]:
# Create array with NumPy
my_matrix = np.array(
    [[3,  2,  -17],
     [7,  8,    4],
     [6,  3,   pi]
])

# Convert to SymPy matrice formating
sp.Matrix(my_matrix)

Matrix([
[3, 2, -17],
[7, 8,   4],
[6, 3,  pi]])

In [212]:
# Swap row 3 and 2 by reassigning index
my_matrix[[2,1]] = my_matrix[[1,2]]

sp.Matrix(my_matrix)

Matrix([
[3, 2, -17],
[6, 3,  pi],
[7, 8,   4]])

In [213]:
min_matris = sp.Matrix(my_matrix)

# How to swap with SymPy (swapping back rows)
min_matris.row_swap(1,0)

min_matris

Matrix([
[6, 3,  pi],
[3, 2, -17],
[7, 8,   4]])

In [214]:
# convert back to NumPy
my_matrix = np.array(min_matris)

# multiply row 1 by 1/2
my_matrix[0] = np.multiply(my_matrix[0],0.5)

sp.Matrix(my_matrix)

Matrix([
[3.0, 1.5, 0.5*pi],
[  3,   2,    -17],
[  7,   8,      4]])

In [215]:
# Row addition works by multiplying one row in the matrix and then adding it to another row.

# Easy example matrix:
B = np.matrix(
    [[1,-2],
     [-4,9]])

# Multiply row 1 by 4 and add it to row 2:
B[1] = B[1]+B[0]*4

sp.Matrix(B)

Matrix([
[1, -2],
[0,  1]])

---

## #numpy.linalg.solve

numpy.linalg.solve requires A to be square:

 $$A * x = b$$

where $A$ is a matrix of coefficients, $x$ is a vector of variables, and $b$ is a vector of constants.

 
Gaussian elimination with row interchanges is used to factor $A$ as $A$ = P * L * U , where
 
### **P:** permutation matrix
   Square matrix with exactly one 1 in each row and each column, with all other entries being 0:

$$\begin{bmatrix} 0 & 1 & 0 & 0 \\ 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix}$$
   
### **L:** unit lower triangular
   square matrix with 1s on the diagonal (i.e., the entries where the row and column indices are the same) and 0s above the diagonal:

   $$\begin{bmatrix} 1 & 0 & 0 & 0 \\ 4 & 1 & 0 & 0 \\ 7 & 5 & 1 & 0 \\ 2 & 6 & 8 & 1 \end{bmatrix}$$
   
### **U:** upper triangular
   a square matrix that has 0s below the diagonal:

   $$\begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 5 & 6 & 7 \\ 0 & 0 & 8 & 9 \\ 0 & 0 & 0 & 10 \end{bmatrix}$$


 
 The factored form of A is then used to solve the above system.

---

 Ok, let's reset the matrix to something easy, say we have the equations:
$$3x + 4y = 8$$
$$x - 2y = -4$$

In [216]:
# we can write it in the form Ax = b as follows:

# coefficients matrix
A = [[3, 4],
     [1, -2]]

# vector of variables
x = [[x],
     [y]]

# vector of constants
b = [[8],
     [-4]]

# Same but with NumPy
A = np.array([[3, 4],
              [1, -2]])
b = np.array([[8],
              [-4]])

solution = np.linalg.solve(A, b)

solution

array([[0.],
       [2.]])

This returns the solution vector as np.array:

```
array([[0.],
       [2.]])
 ```

which we can then use to find the values of x and y that satisfy the original equations.

In [217]:
x, y = solution[0], solution[1]

print(3*x + 4*y == 8)
print(x - 2*y == -4)

[ True]
[ True]


In [218]:
# Create array with NumPy
my_matrix = np.array(
    [[1,  1,  1],
     [1, 4,    -4],
     [0,  1,   1]
])

my_matrix

array([[ 1,  1,  1],
       [ 1,  4, -4],
       [ 0,  1,  1]])

---

In [219]:
# with random integers
arr3 = np.random.randint(-8,8, size=(4,4))

print(arr3)
print(f'Sum = {np.sum(arr3)}') # sum
print(f'Sum along diagonals = {np.trace(arr3)}')

print(np.linalg.inv(arr3))

[[ 6 -8  7  6]
 [-4  5  0 -4]
 [ 7  3  7  2]
 [-8  3 -7  0]]
Sum = 15
Sum along diagonals = 18
[[-0.14049587 -0.19008264  0.04132231 -0.09917355]
 [-0.04958678 -0.00826446  0.1322314   0.08264463]
 [ 0.13931523  0.2136954   0.0094451   0.00590319]
 [ 0.0785124  -0.07024793  0.12396694  0.20247934]]


In [220]:
np.linalg.inv(arr3)

array([[-0.14049587, -0.19008264,  0.04132231, -0.09917355],
       [-0.04958678, -0.00826446,  0.1322314 ,  0.08264463],
       [ 0.13931523,  0.2136954 ,  0.0094451 ,  0.00590319],
       [ 0.0785124 , -0.07024793,  0.12396694,  0.20247934]])

In [221]:
a = np.array([[0,1,-2],[3,4,5],[6,7,-8]])

print(type(a),a.ndim)
print(a)
print()
print(type(a))
print(a.shape, a.ndim)

sp.Matrix(a)

<class 'numpy.ndarray'> 2
[[ 0  1 -2]
 [ 3  4  5]
 [ 6  7 -8]]

<class 'numpy.ndarray'>
(3, 3) 2


Matrix([
[0, 1, -2],
[3, 4,  5],
[6, 7, -8]])

In [222]:
## 2D vector rotation
def rotate_matrix(matrix):
  transposed_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
  
  # reverse the rows of the transposed matrix
  return [row[::-1] for row in transposed_matrix]

# rotate the matrix
a = rotate_matrix(a)

a = np.array(a)

sp.Matrix(a)

Matrix([
[ 6, 3,  0],
[ 7, 4,  1],
[-8, 5, -2]])

In [223]:
arr = np.random.randint(-2, 4, size=(3, 3))

print(arr)
np.linalg.solve(arr,[2,4,0])

[[ 2  1  2]
 [ 3 -1  2]
 [ 2  1 -1]]


array([ 0.66666667, -0.66666667,  0.66666667])

In [224]:
arr1 = sp.Matrix(np.linalg.solve(arr,[2,4,0]).astype(int))
arr1

Matrix([
[0],
[0],
[0]])

## #RREF 
##### *Reduced Row Echelon Form* (=reducerad trappstegsform)
is a way of putting a matrix into a specific standard form, which can make it easier to solve systems of linear equations. In order for a matrix to be in RREF, it must satisfy the following conditions:

```
1. All rows with non-zero entries must be above any rows of all zeros.
2. The first non-zero entry in each row, called the "leading coefficient", must be 1.
3. Each leading coefficient must be the only non-zero entry in its column.
```

For example, the matrix:

$$\begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 1 & 2 & 3 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

is in RREF, because all of the conditions are satisfied. On the other hand, the matrix:


$$\begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 1 & 2 & 3 \\ 0 & 0 & 1 & 0 \end{bmatrix}$$

is not in RREF, because the third row does not satisfy condition 3 (the leading coefficient, 1, is not the only non-zero entry in its column). To put this matrix into RREF, we would need to perform some row operations, such as swapping rows or multiplying rows by constants, to make it satisfy all three conditions.

In [225]:
a = sp.Matrix([
[1, 2, 3, 4],
[0, 1, 2, 3],
[0, 0, 1, 0],
])

a = a.rref()

a

(Matrix([
 [1, 0, 0, -2],
 [0, 1, 0,  3],
 [0, 0, 1,  0]]),
 (0, 1, 2))

When using the `rref()` function from the SymPy library, the output will be the reduced row echelon form of the given matrix, as well as a tuple of indices of the pivot columns.

As mentioned above:

**pivot columns** <==> columns of the matrix that contain the **leading coefficients of each row**

In [226]:
a = sp.Matrix([
    [1, -2, 3, 5, 14], 
    [-2, 4, -5, -10, -26],
    [2, -4, 6, 11, 29],
    [-1, 2, -2, -5, -12]]
)

a.rref()

(Matrix([
 [1, -2, 0, 0, 3],
 [0,  0, 1, 0, 2],
 [0,  0, 0, 1, 1],
 [0,  0, 0, 0, 0]]),
 (0, 2, 3))