### Linear systems of equations
- augmented matrix (utökad matris).
- Gaussian elimination
- reduced row echelon form (reducerad trappstegsform)
- pivot columns, bound and free varibles

- sympy.rref
- scipy.linalg.solve

In [67]:
import numpy as np

# Three dimensional array

a = np.array([[[0,1,2],[3,4,5],[6,7,8]],
              [[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]],
              [[1,2,3],[4,5,6],[7,8,9]]])

print(type(a),a.ndim)
a

<class 'numpy.ndarray'> 3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [78]:
# Convert 3D array to 2D
a2d = np.reshape(a, (3,9))

print(type(a2d), a2d.ndim, a2d.size, a2d.shape)
a2d

<class 'numpy.ndarray'> 2 27 (3, 9)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1, -2, -3, -4, -5, -6, -7, -8, -9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

ndarrays are immutable, as such we cannot remove elements, however we can create new arrays

numpy.linalg.solve requires A to be square:

 A * X = B, where A is a square matrix and X and B are rectangular matrices or vectors.
 
 Gaussian elimination with row interchanges is used to factor A as A = P * L * U , where
 - P = permutation matrix
 - L = unit lower triangular
 - U = is upper triangular.
 
 The factored form of A is then used to solve the above system.

 ---

 Let's create a square matrix and do some basic operations:

In [148]:
from math import pi

my_matrix = np.matrix(
    [[3,  2,  -17],
     [7,  8,    4],
     [6,  3,   pi]
])

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  7.        ,   8.        ,   4.        ],
        [  6.        ,   3.        ,   3.14159265]])

In [149]:
# swap rows by reassigning index
my_matrix[[2,1]] = my_matrix[[1,2]]

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  6.        ,   3.        ,   3.14159265],
        [  7.        ,   8.        ,   4.        ]])

In [150]:
# multiply row 3 by 1/2
my_matrix[2] = np.multiply(my_matrix[2],0.5)

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  6.        ,   3.        ,   3.14159265],
        [  3.5       ,   4.        ,   2.        ]])

In [158]:
# Row addition works by multiplying one row in the matrix and then adding it to another row.
# For example, in the matrix below, we can multiply row 1 by 4 and add it to row 2:

B = np.matrix(
    [[1,-2],
     [-4,9]])

B[1] = B[1]+B[0]*4

B

matrix([[ 1, -2],
        [ 0,  1]])

---

In [107]:
# with random integers
arr3 = np.random.randint(-8,8, size=(4,4))

print(arr3)
print(f'Sum = {np.sum(arr3)}') # sum
print(f'Sum along diagonals = {np.trace(arr3)}')

print(np.linalg.inv(arr3))

[[-1 -3  7  3]
 [ 0  4 -7  1]
 [ 3  0 -6 -7]
 [ 0 -6  3 -8]]
Sum = -17
Sum along diagonals = -11
[[ 0.36734694 -0.14285714  0.45578231 -0.27891156]
 [-1.08163265 -0.85714286 -0.36054422 -0.19727891]
 [-0.53061224 -0.57142857 -0.17687075 -0.11564626]
 [ 0.6122449   0.42857143  0.20408163 -0.02040816]]


In [97]:
np.linalg.inv(arr3)

array([[ 1.03932584, -0.50561798, -0.88202247, -0.08988764],
       [ 0.0252809 , -0.03932584,  0.0758427 , -0.12921348],
       [ 0.25842697, -0.17977528, -0.2247191 ,  0.12359551],
       [ 1.06741573, -0.43820225, -0.79775281, -0.01123596]])

In [110]:
a = np.matrix([1, 2, 3])

print(a)
print()
print(type(a))
print(a.shape, a.ndim)

[[1 2 3]]

<class 'numpy.matrix'>
(1, 3) 2


In [6]:
def get_rotation_matrix(theta, axis):
    """
    Returns a 3x3 rotation matrix with the given theta and axis
    """

    axis = np.array(axis)
    axis = axis / np.linalg.norm(axis)
    a = np.cos(theta / 2)
    b, c, d = -axis * np.sin(theta / 2)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)]])

In [13]:
get_rotation_matrix(a,1)

array([[[[[ 0.54030231, -0.41614684, -0.9899925 ],
          [-0.65364362,  0.28366219,  0.96017029],
          [ 0.75390225, -0.14550003, -0.91113026]],

         [[ 0.54030231, -0.41614684, -0.9899925 ],
          [-0.65364362,  0.28366219,  0.96017029],
          [ 0.75390225, -0.14550003, -0.91113026]],

         [[ 0.54030231, -0.41614684, -0.9899925 ],
          [-0.65364362,  0.28366219,  0.96017029],
          [ 0.75390225, -0.14550003, -0.91113026]]],


        [[[-0.38177329,  0.50684941,  1.84887249],
          [ 2.41044612,  1.67526209,  0.31924521],
          [-0.41088885,  0.15614179,  1.49901178]],

         [[-0.38177329,  0.50684941,  1.84887249],
          [ 2.41044612,  1.67526209,  0.31924521],
          [-0.41088885,  0.15614179,  1.49901178]],

         [[-0.38177329,  0.50684941,  1.84887249],
          [ 2.41044612,  1.67526209,  0.31924521],
          [-0.41088885,  0.15614179,  1.49901178]]],


        [[[ 1.30116868,  2.32544426,  2.1311125 ],
          [ 0.8