### Linear systems of equations
- augmented matrix (utökad matris).
- Gaussian elimination
- reduced row echelon form (reducerad trappstegsform)
- pivot columns, bound and free varibles

- sympy.rref
- scipy.linalg.solve

In [1]:
import numpy as np

# Three dimensional array

a = np.array([[[0,1,2],[3,4,5],[6,7,8]],
              [[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]],
              [[1,2,3],[4,5,6],[7,8,9]]])

print(type(a),a.ndim)
a

<class 'numpy.ndarray'> 3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [2]:
# Convert 3D array to 2D
a2d = np.reshape(a, (3,9))

print(type(a2d), a2d.ndim, a2d.size, a2d.shape)
a2d

<class 'numpy.ndarray'> 2 27 (3, 9)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [-1, -2, -3, -4, -5, -6, -7, -8, -9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

ndarrays are immutable, as such we cannot remove elements, however we can create new arrays

numpy.linalg.solve requires A to be square:

 A * X = B, where A is a square matrix and X and B are rectangular matrices or vectors.
 
 Gaussian elimination with row interchanges is used to factor A as A = P * L * U , where
 - P = permutation matrix
 - L = unit lower triangular
 - U = is upper triangular.
 
 The factored form of A is then used to solve the above system.

 ---

 Let's create a square matrix and do some basic operations:

In [38]:
from math import pi

my_matrix = np.matrix(
    [[3,  2,  -17],
     [7,  8,    4],
     [6,  3,   pi]
])

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  7.        ,   8.        ,   4.        ],
        [  6.        ,   3.        ,   3.14159265]])

In [4]:
# swap rows by reassigning index
my_matrix[[2,1]] = my_matrix[[1,2]]

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  6.        ,   3.        ,   3.14159265],
        [  7.        ,   8.        ,   4.        ]])

In [5]:
# multiply row 3 by 1/2
my_matrix[2] = np.multiply(my_matrix[2],0.5)

my_matrix

matrix([[  3.        ,   2.        , -17.        ],
        [  6.        ,   3.        ,   3.14159265],
        [  3.5       ,   4.        ,   2.        ]])

In [6]:
# Row addition works by multiplying one row in the matrix and then adding it to another row.
# For example, in the matrix below, we can multiply row 1 by 4 and add it to row 2:

B = np.matrix(
    [[1,-2],
     [-4,9]])

B[1] = B[1]+B[0]*4

B

matrix([[ 1, -2],
        [ 0,  1]])

---

In [7]:
# with random integers
arr3 = np.random.randint(-8,8, size=(4,4))

print(arr3)
print(f'Sum = {np.sum(arr3)}') # sum
print(f'Sum along diagonals = {np.trace(arr3)}')

print(np.linalg.inv(arr3))

[[ 7  1 -3  0]
 [ 6  6  6 -2]
 [ 6 -5 -4  4]
 [ 3 -6 -8  0]]
Sum = 11
Sum along diagonals = 9
[[-0.01603206  0.10420842  0.05210421  0.05811623]
 [ 0.33667335 -0.18837675 -0.09418838 -0.22044088]
 [-0.25851703  0.18036072  0.09018036  0.06212425]
 [ 0.18637275 -0.21142285  0.14428858 -0.3006012 ]]


In [8]:
np.linalg.inv(arr3)

array([[-0.01603206,  0.10420842,  0.05210421,  0.05811623],
       [ 0.33667335, -0.18837675, -0.09418838, -0.22044088],
       [-0.25851703,  0.18036072,  0.09018036,  0.06212425],
       [ 0.18637275, -0.21142285,  0.14428858, -0.3006012 ]])

In [104]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(type(a),a.ndim)
print(a)
print()
print(type(a))
print(a.shape, a.ndim)

<class 'numpy.ndarray'> 2
[[0 1 2]
 [3 4 5]
 [6 7 8]]

<class 'numpy.ndarray'>
(3, 3) 2


In [137]:
## 2D vector rotation
def rotate_matrix(matrix):
  transposed_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
  
  # reverse the rows of the transposed matrix
  return [row[::-1] for row in transposed_matrix]

# rotate the matrix
a = rotate_matrix(a)

a = np.array(a)

a

array([[6, 3, 0],
       [7, 4, 1],
       [8, 5, 2]])

In [10]:
def get_rotation_matrix(theta, axis):
    """
    Returns a 3x3 rotation matrix with the given theta and axis
    """

    axis = np.array(axis)
    axis = axis / np.linalg.norm(axis)
    a = np.cos(theta / 2)
    b, c, d = -axis * np.sin(theta / 2)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)]])