### Linear systems of equations
- augmented matrix (utökad matris).
- Gaussian elimination
- reduced row echelon form (=reducerad trappstegsform) (sympy.rref)
- pivot columns, bound and free varibles

- scipy.linalg.solve

In [241]:
import numpy as np
import sympy as sp

x, y, z, pi = sp.symbols('x,y,z, pi')

# Two dimensional array
a = np.array([[0,1,2],[pi,4,5],[-1,-2,-3]], dtype=object)

print(type(a), a.ndim, a.size, a.shape)
a


<class 'numpy.ndarray'> 2 9 (3, 3)


array([[0, 1, 2],
       [pi, 4, 5],
       [-1, -2, -3]], dtype=object)

In [242]:
# As sympy matrice
sp.Matrix(a)

Matrix([
[ 0,  1,  2],
[pi,  4,  5],
[-1, -2, -3]])

In [243]:
# formats
x = 12
print('a = ', 2*np.sqrt(x)) # regualar print in IDE
sp.pprint(2*sp.sqrt(x)) # prettyprinter module
2*sp.sqrt(x) # jupyter notebook output as sympy symbols

a =  6.928203230275509
4⋅√3


4*sqrt(3)

Sympy matrices are mutable while ndarrays are immutable.

numpy.linalg.solve requires A to be square:

 A * X = B, where A is a square matrix and X and B are rectangular matrices or vectors.
 
 Gaussian elimination with row interchanges is used to factor A as A = P * L * U , where
 - P = permutation matrix
 - L = unit lower triangular
 - U = is upper triangular.
 
 The factored form of A is then used to solve the above system.

 ---

 Let's create a square matrix and do some basic operations:

In [244]:
def get_grid():



    def get_row():

        # randomize key pair
        my_pair = np.random.randint([-8,0], [0,8])

         # appends random element from pool to end of key pair
        pool_of_constants = [pi, sp.Rational(2,3), 0, sp.Rational(1/4)]

        return np.append(my_pair, pool_of_constants[np.random.randint(0,4)])

    # create matrix
    a = np.array(
        [get_row(),
         get_row(),
         get_row()
    ])


    return a

a = get_grid()

sp.Matrix(a)

Matrix([
[-4, 6, 1/4],
[-1, 6,  pi],
[-3, 5, 1/4]])

In [245]:
r = sp.Rational(1,4)
print(r)

1/4


In [246]:
# fractions will not convert, issues with float to int type conversions probably

In [247]:
# Create array with NumPy
my_matrix = np.array(
    [[3,  2,  -17],
     [7,  8,    4],
     [6,  3,   pi]
])

# Convert to SymPy matrice formating
sp.Matrix(my_matrix)

Matrix([
[3, 2, -17],
[7, 8,   4],
[6, 3,  pi]])

In [248]:
# Swap row 3 and 2 by reassigning index
my_matrix[[2,1]] = my_matrix[[1,2]]

sp.Matrix(my_matrix)

Matrix([
[3, 2, -17],
[6, 3,  pi],
[7, 8,   4]])

In [249]:
min_matris = sp.Matrix(my_matrix)

# How to swap with SymPy (swapping back rows)
min_matris.row_swap(1,0)

min_matris

Matrix([
[6, 3,  pi],
[3, 2, -17],
[7, 8,   4]])

In [250]:
# convert back to NumPy
my_matrix = np.array(min_matris)

# multiply row 1 by 1/2
my_matrix[0] = np.multiply(my_matrix[0],0.5)

sp.Matrix(my_matrix)

Matrix([
[3.0, 1.5, 0.5*pi],
[  3,   2,    -17],
[  7,   8,      4]])

In [251]:
# Row addition works by multiplying one row in the matrix and then adding it to another row.
# For example, in the matrix below, we can multiply row 1 by 4 and add it to row 2:

B = np.matrix(
    [[1,-2],
     [-4,9]])

B[1] = B[1]+B[0]*4

sp.Matrix(B)

Matrix([
[1, -2],
[0,  1]])

---

In [252]:
# with random integers
arr3 = np.random.randint(-8,8, size=(4,4))

print(arr3)
print(f'Sum = {np.sum(arr3)}') # sum
print(f'Sum along diagonals = {np.trace(arr3)}')

print(np.linalg.inv(arr3))

[[ 1  4 -7  5]
 [-8  4  4 -1]
 [ 2 -4 -8  0]
 [-7 -7 -2 -1]]
Sum = -25
Sum along diagonals = -4
[[-0.02714165 -0.07633588  0.00042409 -0.05937235]
 [ 0.00169635  0.12977099  0.09372349 -0.12128923]
 [-0.00763359 -0.08396947 -0.17175573  0.04580153]
 [ 0.19338422 -0.20610687 -0.31552163  0.17302799]]


In [253]:
np.linalg.inv(arr3)

array([[-0.02714165, -0.07633588,  0.00042409, -0.05937235],
       [ 0.00169635,  0.12977099,  0.09372349, -0.12128923],
       [-0.00763359, -0.08396947, -0.17175573,  0.04580153],
       [ 0.19338422, -0.20610687, -0.31552163,  0.17302799]])

In [254]:
a = np.array([[0,1,-2],[3,4,5],[6,7,-8]])

print(type(a),a.ndim)
print(a)
print()
print(type(a))
print(a.shape, a.ndim)

sp.Matrix(a)

<class 'numpy.ndarray'> 2
[[ 0  1 -2]
 [ 3  4  5]
 [ 6  7 -8]]

<class 'numpy.ndarray'>
(3, 3) 2


Matrix([
[0, 1, -2],
[3, 4,  5],
[6, 7, -8]])

In [255]:
## 2D vector rotation
def rotate_matrix(matrix):
  transposed_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
  
  # reverse the rows of the transposed matrix
  return [row[::-1] for row in transposed_matrix]

# rotate the matrix
a = rotate_matrix(a)

a = np.array(a)

sp.Matrix(a)

Matrix([
[ 6, 3,  0],
[ 7, 4,  1],
[-8, 5, -2]])

In [258]:
a = np.array([[ 6,  3,  0],
       [ 7,  4,  1],
       [-8,  5, pi]])

a

array([[6, 3, 0],
       [7, 4, 1],
       [-8, 5, pi]], dtype=object)

In [ ]:
def get_rotation_matrix(theta, axis):
    """
    Returns a 3x3 rotation matrix with the given theta and axis
    """

    axis = np.array(axis)
    axis = axis / np.linalg.norm(axis)
    a = np.cos(theta / 2)
    b, c, d = -axis * np.sin(theta / 2)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)]])