This game is inspired by Hearthstone and is like, a two-player (or two-computer) game in which each player draws card units from a set, places them on their side of the board and then let the units fight each other.

At the end of each battle, the ammount of units left on each side translates to the total damage dealt to the opposing player. When a player reaches 0 HP, the game is over.

Some ideas:

- Have multiple matrices (overlaying boards) for attack value and defense values for each unit, not just health.
    - Or just have vectors in the matrice containing stats for the unit??
    - if we do this, another layout would be needed, as the current layout only handles one value for each unit
    - but it would be cool to do and make it much more interesting and lärorikt i guess

    <br>

- Have units which buffs other units if they are placed next to them.

- Have units merge if they are similar in some way??
    - This also means having to create different unit-types, which would be fun!

    <br>

- Have units move to different spaces. This is an intersting one. Maybe attack could increase if some units are closer?

TODO:

How should the units be distributed between the players? How should it be randomized? Just draw a couple from a deck probably.

Adjust attack patterns. Right now its simply just row subtraction.


Also, this is written to work with jupyter notebook, some adjustments needed for .py to avoid re-running functions etc.

In [1]:
# Generating board, any 2 dimensional size should work
import numpy as np
board = np.zeros((8,8)) # but lower are better for testing
print(board)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:

# Player health, players lose one HP per unit left on opponent side after battle phase
P1_health = len(board) * 4
P2_health = len(board) * 4

# Player name
P1 = 'P1 Fried'
P2 = 'P2 Toast'

# Testing health values of units in hand to be placed on the board
# this should probably be a hand drawn from a deck, like, draw one card each turn, start with 3 or smt
# maybe write algos to make predictions on which cards to play
# i mean at the current state the best algo would just play the card with the highest health value, but adding more parameters could make it interesting
P1_hand = [0,0,0,0]
P2_hand = [0,0,0,0]

# if we do the vector idea (which we totally should) these would represent playable card units
# rn for testing it only represents UNIT HEALTH 
P1_deck = [1,2,3,4,5,6,7,8,9]
P2_deck = [1,2,3,4,5,6,7,8,9]

# pretty good function, works with lists
np.random.shuffle(P1_deck)
np.random.shuffle(P2_deck)

P1_deck, P2_deck

([3, 6, 9, 2, 4, 5, 8, 7, 1], [8, 4, 1, 3, 5, 6, 7, 9, 2])

In [3]:
def draw_card(player, hand, deck, n=1):
    """Takes top card in player deck and places in in hand.
       Removes drawn card from deck.
       If player hand is full (no 0:s), returns None.
       
       Defaults to 1 card.
    """

    print(f'{draw_card} running for {player}, drawing {n} cards.')

    for i in range(n): # allows multiple cards to be drawn

        # if hand is full
        if np.count_nonzero(hand) >= len(hand):
            return None

        for i, card in enumerate(hand):
            if card == 0:
                break
            
        print(f'Current {hand=}. {player} has drawn {deck[0]}')
        hand[i] = deck[0]
        print(f'New {hand=}')
        deck.pop(0)

    return hand, deck

def remove_card(player, hand):
    hand.pop(0) # remove first card
    hand.append(0) # make room for new cards by expanding array with a 0
    print(f'Card removed from {player} hand. New {hand=}')
    return hand


def select_card(player, hand):
    
    pass
    

In [4]:
sum(P1_hand), len(P1_deck)

(0, 9)

In [5]:
def place_unit(board, player, player_hand):
    if sum(player_hand) == 0:
        print('Hand is empty. No unit to place!')
        return None

    # max values might not be needed after all, but good for testing different board sizes
    max_width = len(board[0])-1
    max_height = len(board)-1

    try:
        x, y = select_tile(board, max_width, max_height, player) # tuple unpacking of coords for unit placement

        board[x,y] = player_hand[0]

        print(f'{player} placed a unit with health {player_hand[0]} at {[x+1,y+1]}')
        remove_card(player, player_hand)
        return board

    except:
        print(f'Cannot find tile, {player} unit row is full!')
        return board

def select_tile(board, max_x, max_y, player) -> tuple:
    """Finds available tile to place unit on board.
    Starts on the left and continues for each available column for each player
    TODO: Maybe shuffle units, or make old units get pushed to the right once new ones are placed?
    """

    print(f'{select_tile} running for {player=}')

    # if board is full for either player, return None
    if player == P1 and board[max_x][-1] != 0 or player == P2 and board[0][-1] !=0:
        return None

    # find available tile for P1 (bottom row) and P2 (top row)
    if player == P1:
        row = max_x
        column = 0
        while board[row][column] != 0:
            column +=1
        return row, column

    #P2
    row = 0
    column = 0
    while board[row][column] != 0:
        column +=1
    return row, column

In [6]:
for length in P1_hand:
    try:
        P1_hand, P1_deck = draw_card(P1, P1_hand, P1_deck)
        P2_hand, P2_deck = draw_card(P2, P2_hand, P2_deck)
    except:
        print(f'Hand is full = {P1_hand}. {draw_card} aborted!')

<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Current hand=[0, 0, 0, 0]. P1 Fried has drawn 3
New hand=[3, 0, 0, 0]
<function draw_card at 0x10e7dedc0> running for P2 Toast, drawing 1 cards.
Current hand=[0, 0, 0, 0]. P2 Toast has drawn 8
New hand=[8, 0, 0, 0]
<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Current hand=[3, 0, 0, 0]. P1 Fried has drawn 6
New hand=[3, 6, 0, 0]
<function draw_card at 0x10e7dedc0> running for P2 Toast, drawing 1 cards.
Current hand=[8, 0, 0, 0]. P2 Toast has drawn 4
New hand=[8, 4, 0, 0]
<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Current hand=[3, 6, 0, 0]. P1 Fried has drawn 9
New hand=[3, 6, 9, 0]
<function draw_card at 0x10e7dedc0> running for P2 Toast, drawing 1 cards.
Current hand=[8, 4, 0, 0]. P2 Toast has drawn 1
New hand=[8, 4, 1, 0]
<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Current hand=[3, 6, 9, 0]. P1 Fried has drawn 2
New han

In [7]:
sum(P1_hand), len(P1_deck)

(20, 5)

In [8]:
try:
    P1_hand, P1_deck = draw_card(P1, P1_hand, P1_deck)
    P2_hand, P2_deck = draw_card(P2, P2_hand, P2_deck)
except:
    print(f'Hand is full. {draw_card} aborted!')

<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Hand is full. <function draw_card at 0x10e7dedc0> aborted!


In [9]:
sum(P1_hand), len(P1_deck)

(20, 5)

In [10]:
# testing to place basic units
for length in board:
    place_unit(board, player=P1, player_hand=P1_hand)
    place_unit(board, player=P2, player_hand=P2_hand)
board

<function select_tile at 0x10e7f01f0> running for player='P1 Fried'
P1 Fried placed a unit with health 3 at [8, 1]
Card removed from P1 Fried hand. New hand=[6, 9, 2, 0]
<function select_tile at 0x10e7f01f0> running for player='P2 Toast'
P2 Toast placed a unit with health 8 at [1, 1]
Card removed from P2 Toast hand. New hand=[4, 1, 3, 0]
<function select_tile at 0x10e7f01f0> running for player='P1 Fried'
P1 Fried placed a unit with health 6 at [8, 2]
Card removed from P1 Fried hand. New hand=[9, 2, 0, 0]
<function select_tile at 0x10e7f01f0> running for player='P2 Toast'
P2 Toast placed a unit with health 4 at [1, 2]
Card removed from P2 Toast hand. New hand=[1, 3, 0, 0]
<function select_tile at 0x10e7f01f0> running for player='P1 Fried'
P1 Fried placed a unit with health 9 at [8, 3]
Card removed from P1 Fried hand. New hand=[2, 0, 0, 0]
<function select_tile at 0x10e7f01f0> running for player='P2 Toast'
P2 Toast placed a unit with health 1 at [1, 3]
Card removed from P2 Toast hand. Ne

array([[8., 4., 1., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 6., 9., 2., 0., 0., 0., 0.]])

In [11]:
sum(P1_hand), len(P1_deck)

(0, 5)

In [12]:
place_unit(board, player=P1, player_hand=P1_hand)

Hand is empty. No unit to place!


In [13]:
sum(P1_hand), len(P1_deck)

(0, 5)

In [14]:
# Entire function is broken and should be rewritten from scratch

def battle_phase(board, P1_health, P2_health):

    # so right now this is a very boring attack pattern, it just mirrors the same column values and subtracts
    P2_row = board[0]-board[-1]
    P1_row = board[-1]-board[0]

    # remove units if health is < 0
    board[0] = [0 if i < 0 else i for i in P2_row]
    board[-1] = [0 if i < 0 else i for i in P1_row]

    # count non-zero values for units left/damage dealt
    P2_units_left, P1_units_left = np.count_nonzero(board[0]), np.count_nonzero(board[-1])

    print(f'P2: {board[0]}, units left = {P2_units_left}')
    print(f'P1: {board[-1]}, units left = {P1_units_left}')

    if P2_units_left > P1_units_left:
        P1_health -= P2_units_left
        print(f'P2 dealt {P2_units_left} damage to P1.')

    elif P1_units_left > P2_units_left:
        P2_units_left -= P1_units_left
        print(f'P1 dealt {P1_units_left} damage to P2.')

    else:
        print('Draw, no damage dealt.')
    
    return board, P2_units_left, P1_units_left

board, P2_units_left, P1_units_left = battle_phase(board, P2_health, P1_health)

P1_health -= P2_units_left
P2_health -= P1_units_left
print(f'{P1_health=}, {P2_health=}')

P2: [5. 0. 0. 1. 0. 0. 0. 0.], units left = 2
P1: [0. 2. 8. 0. 0. 0. 0. 0.], units left = 2
Draw, no damage dealt.
P1_health=30, P2_health=30


The entire battle_phase will have to be refactored for multiple matrices. Maybe the best idea is to have the main board containing vectors which represents the unit, with each vector holding the health, attack etc. values?

But for now, it's just simply health and attack as the same value for the same position on the board.

So if for example we're left with this board:

```
P2: [1. 1. 1. 1.], units left = 4
P1: [0. 0. 0. 0.], units left = 0
P2 dealt 4 damage to P1.
````
P2 would not be able to place any more units the next turn. So we have to make a decision on how to handle that.
If we leave it as is, the player who wins the turn will be much less likely to win the next turn, given the remaining units will have on average much lower health, while P1 will be able to place new units with full health.

On the other hand, if we incorporate a 'card draw' mechanic, the player who's not able to place any units will have more cards(units) to place the next turn.

I guess we'll just have to experiment.



In [15]:
P1_hand, P2_hand # should be all 0

([0, 0, 0, 0], [0, 0, 0, 0])

In [16]:
len(P2_deck), len(P1_deck) # remaining cards in deck seem to work. need error handling for when deck is empty

(5, 5)

In [17]:
try:
    P1_hand, P1_deck = draw_card(P1, P1_hand, P1_deck)
    P2_hand, P2_deck = draw_card(P2, P2_hand, P2_deck)
except:
    print(f'Hand is full. {draw_card} aborted!')

<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 1 cards.
Current hand=[0, 0, 0, 0]. P1 Fried has drawn 4
New hand=[4, 0, 0, 0]
<function draw_card at 0x10e7dedc0> running for P2 Toast, drawing 1 cards.
Current hand=[0, 0, 0, 0]. P2 Toast has drawn 5
New hand=[5, 0, 0, 0]


In [18]:
board

array([[5., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 8., 0., 0., 0., 0., 0.]])

In [19]:
place_unit(board, player=P1, player_hand=P1_hand)
place_unit(board, player=P2, player_hand=P2_hand)
board

<function select_tile at 0x10e7f01f0> running for player='P1 Fried'
P1 Fried placed a unit with health 4 at [8, 1]
Card removed from P1 Fried hand. New hand=[0, 0, 0, 0]
<function select_tile at 0x10e7f01f0> running for player='P2 Toast'
P2 Toast placed a unit with health 5 at [1, 2]
Card removed from P2 Toast hand. New hand=[0, 0, 0, 0]


array([[5., 5., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 2., 8., 0., 0., 0., 0., 0.]])

Nice, placing units/cards wherever space is available, starting from left to right, works for both players.

I still haven't decided where new units should be placed <=> where available space (0:s) should be placed.

In [20]:
board, P2_units_left, P1_units_left = battle_phase(board, P2_health, P1_health)

P1_health -= P2_units_left
P2_health -= P1_units_left
print(f'{P1_health=}, {P2_health=}')

P2: [1. 3. 0. 1. 0. 0. 0. 0.], units left = 3
P1: [0. 0. 8. 0. 0. 0. 0. 0.], units left = 1
P2 dealt 3 damage to P1.
P1_health=27, P2_health=29


In [21]:
P1_deck, P2_deck, P1_hand, P2_hand

([5, 8, 7, 1], [6, 7, 9, 2], [0, 0, 0, 0], [0, 0, 0, 0])

In [22]:
try:
    P1_hand, P1_deck = draw_card(P1, P1_hand, P1_deck, n=3)
    P2_hand, P2_deck = draw_card(P2, P2_hand, P2_deck, n=3)
except:
    print(f'Hand is full. {draw_card} aborted!')

<function draw_card at 0x10e7dedc0> running for P1 Fried, drawing 3 cards.
Current hand=[0, 0, 0, 0]. P1 Fried has drawn 5
New hand=[5, 0, 0, 0]
Current hand=[5, 0, 0, 0]. P1 Fried has drawn 8
New hand=[5, 8, 0, 0]
Current hand=[5, 8, 0, 0]. P1 Fried has drawn 7
New hand=[5, 8, 7, 0]
<function draw_card at 0x10e7dedc0> running for P2 Toast, drawing 3 cards.
Current hand=[0, 0, 0, 0]. P2 Toast has drawn 6
New hand=[6, 0, 0, 0]
Current hand=[6, 0, 0, 0]. P2 Toast has drawn 7
New hand=[6, 7, 0, 0]
Current hand=[6, 7, 0, 0]. P2 Toast has drawn 9
New hand=[6, 7, 9, 0]


In [23]:
P1_deck, P2_deck, P1_hand, P2_hand

([1], [2], [5, 8, 7, 0], [6, 7, 9, 0])

In [24]:
board, P2_units_left, P1_units_left = battle_phase(board, P2_health, P1_health)

P1_health -= P2_units_left
P2_health -= P1_units_left
print(f'{P1_health=}, {P2_health=}')

P2: [1. 3. 0. 1. 0. 0. 0. 0.], units left = 3
P1: [0. 0. 8. 0. 0. 0. 0. 0.], units left = 1
P2 dealt 3 damage to P1.
P1_health=24, P2_health=28


Once again I'm reminded that the battle phase has to be rewritten entirely. Also should make classes.